[project]
name = "wsi-preprocess"
version = "0.2.0"
description = "WSI preprocessing, tissue segmentation, blur filtering, stain normalization and patch extraction library"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "opencv-python-headless",
    "h5py",
    "tiffslide",
    "tqdm",
    "psutil"
]

[project.scripts]
wsi-preprocess = "wsi_preprocess.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/wsi_preprocess"]